/**
 * LIBOTP-NAMETAGS SOFTWARE
 * Copyright (c) loblao.  All rights reserved.
 *
 * All use of this software is subject to the terms of the MIT
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file nametagFloat3d.I
 * @author loblao
 */

NametagFloat3d::NametagFloat3d() : Nametag3d() {
}

NametagFloat3d::~NametagFloat3d() {
}
